# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
HotmartParam.create!([
              { name: 'hottok',
                description: 'Um token único, gerado pelo Hotmart para você produtor. Cada conta possui o seu próprio token, e esta é a garantia que o post está sendo feito pelo Hotmart. Para ver qual é seu token, acesse o hotmart e vá em "Minha Conta -> Configurações Avançadas e API".'}, 
              { name: 'prod',
                description: 'Identificador do Produto que foi adquirido.' }, 
              { name: 'prod_name',
                description: 'Nome do Produto que foi adquirido.' }, 
              { name: 'off',
                description: 'Identificador da Oferta que foi adquirida.' }, 
              { name: 'price',
                description: 'Preço da Oferta no momento da compra.' }, 
              { name: 'aff',
                description: 'Código de afiliado do usuário que indicou a venda do produto.' }, 
              { name: 'aff_name',
                description: 'Nome do usuário que indicou a venda do produto.' }, 
              { name: 'email',
                description: 'Email do comprador.' }, 
              { name: 'name',
                description: 'Nome do comprador.' }, 
              { name: 'first_name',
                description: 'Primeiro nome do comprador.' }, 
              { name: 'last_name',
                description: 'Sobrenome do comprador.' }, 
              { name: 'doc',
                description: 'CPF da pessoa ou documento usado na compra. Ex: 99999999999' }, 
              { name: 'phone_local_code',
                description: 'DDD do telefone. Ex: 99' }, 
              { name: 'phone_number',
                description: 'Número do telefone. Ex: 99999999' }, 
              { name: 'address',
                description: 'Logradouro.' }, 
              { name: 'address_number',
                description: 'Número do endereço.' }, 
              { name: 'address_country',
                description: 'País do comprador.' }, 
              { name: 'address_district',
                description: 'Bairro.' }, 
              { name: 'address_comp',
                description: 'Complemento do endereço.' }, 
              { name: 'address_city',
                description: 'Cidade.' }, 
              { name: 'address_state',
                description: 'Estado. Ex: SP, MG.' }, 
              { name: 'address_zip_code',
                description: 'CEP ou Zip Code. Ex: 99999999' }, 
              { name: 'transaction',
                description: 'Identificador da transação.' }, 
              { name: 'xcod',
                description: 'Identificador customizado pelo usuário, pode ser definido no link de venda para ser recebido de volta (ex: http://hotmart.net.br/show.html?a=555&xcod=meu_codigo_de_controle.' }, 
              { name: 'src',
                description: 'Src (origem) é um código de até 6 caracteres que pode ser customizado pelo usuário para rastrear origens das vendas realizadas (ex: fb, blog, adwrd).' }, 
              { name: 'status',
                description: 'Status da compra (started, approved, canceled, pending_analysis, billet_printed, refunded, completed, blocked, chargeback).' }, 
              { name: 'payment_engine',
                description: 'Envia quem processou a compra (moip ou paypal).' }, 
              { name: 'payment_type',
                description: 'Informa como o comprador pagou (credit_card, billet, bank_transfer, bcash_balance, paypal).' }, 
              { name: 'hotkey',
                description: 'Enviado apenas no caso de Sites de Membros (venda de Acesso à conteúdo restrito). Trata-se do serial único liberado para aquele comprador.' }, 
              { name: 'name_subscription_plan',
                description: 'Enviado apenas em caso de venda de assinaturas. Trata-se do nome do plano adquirido.' }, 
              { name: 'subscriber_code',
                description: 'Enviado apenas em caso de venda de assinaturas. Trata-se do código do assinante.' }, 
              { name: 'cms_marketplace',
                description: 'Tarifa de intermediação e processamento do pagamento.' }, 
              { name: 'cms_vendor',
                description: 'Comissão do produtor gerada nesta transação.' }, 
              { name: 'cms_aff',
                description: 'Comissão do afiliado gerada nesta transação.' }, 
              { name: 'callback_type',
                description: 'Tipo do Callback: 1-compra pagamento unico, 2 - cancelamento assinatura.' }, 
              { name: 'subscription_status',
                description: 'Status da assinatura (active/canceled/past_due/expired).' }, 
              { name: 'transaction_ext',
                description: 'Código de transação gerado pelo meio de pagamento externo (BCash, Paypal, etc).' }, 
              { name: 'sck',
                description: 'sck (origem do checkout) é um código de até 6 caracteres que pode ser customizado pelo usuário para rastrear origens das vendas realizadas em seus checkouts (ex: fb, blog, adwrd).' }
              ])